# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

name: Pull Request Workflow
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  self_test:
    name: 🔬 Self Test
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Check out
        uses: actions/checkout@v6

      - name: ⚙️ Setup uv
        uses: astral-sh/setup-uv@v5

      - name: 🛠️ Run pre-commit
        run: uvx pre-commit run --all-files
